### ISSUE TITLE
Missing steps of Web Access security group creation in the lab-005

### ISSUE THREAD

**Issue by HabibRh26** [thyagomota/aws-labs#15]
in the ALB lab- https://github.com/thyagomota/aws-labs/tree/master/lab-005

during creation of the ALB - creation step of the `web access` security group is missing. what type of rules do I need to add there?

**Comment by thyagomota** [comment]
Both instances should be in a Security Group with inbound rules that accept SSH and HTTP traffic.

**Comment by HabibRh26** [comment]
thank you so much. It worked. 

i would like to give you special thanks to make this repository public as It is helping me greatly to practice hands on lab in my aws account. Additionally, I would like to request, is there any updated copy of this repo since it is a little bit of old to follow along and can I have any intermediate `aws solution architect ` related or `developer associate` related content or lecture notes like this repo from you available on the internet?

your content are helping me a lot. thanks again.

**Comment by thyagomota** [comment]
Thanks for your comments. 

I want to update the material of this repo for a while now.  I just couldn't find the time to do it.  But thanks for reminding me of that. And good luck on your certification. Are you taking the solutions architect anytime soon?

**Comment by HabibRh26** [comment]
> Thanks for your comments.
> 
> I want to update the material of this repo for a while now. I just couldn't find the time to do it. But thanks for reminding me of that. And good luck on your certification. Are you taking the solutions architect anytime soon?

Thanks for your active reply here. 

No, not anytime soon. By this time, If you could share any sort of learning resource related to hands on lab (like yours) for example-` udemy course with hands on lab` or `books with hands on lab` from your vault that can also help me in this journey.

**Comment by thyagomota** [comment]
Try this one from Digital Cloud: https://www.udemy.com/share/102gtM3@CTN5aIW8WFF6m1cI0TlbFQSvrbOFphuR83pN5j9t-mCqbrX-jQXtP-fus3zQO_WT/

**Comment by HabibRh26** [comment]
> Try this one from Digital Cloud: https://www.udemy.com/share/102gtM3@CTN5aIW8WFF6m1cI0TlbFQSvrbOFphuR83pN5j9t-mCqbrX-jQXtP-fus3zQO_WT/

thanks, i am closing this issue.
